name: create-kubernetes-cluster
run-name: ${{ github.actor }}is running for creating Kubernetes Cluster 

#this job included in gcp-snapshot and build job
on:
  workflow_run:
    workflows: ["plan-kubernetes-cluster-azure" ]
    branches: [ main ]
    types:
      - completed

jobs:
  call-kubernetescluster-creation:
    name: Create Kubernetes Cluster
    uses: Naveen-Kollu/ApoTestingCP/.github/workflows/createKubernetesCluster.yml@main
    with:
      environment: 'azure538'
      kubernetestffilesfolder: 'CreateKubernetesCluster'
      gituser: naveen kumar
      gitemailid: naveen538.k@gmail.com
    secrets: inherit
