name: create-kubernetes-cluster
run-name: ${{ github.actor }}is running for creating Kubernetes Cluster 


on:
  workflow_run:
    workflows: ["plan-kubernetes-cluster-azure" ]
    branches: [ main ]
    types:
      - completed

jobs:
  call-kubernetescluster-creation-dev:
    name: Create Kubernetes Cluster in dev environment
    uses: Naveen-Kollu/ApoTestingCP/.github/workflows/createKubernetesCluster.yml@main
    with:
      environment: 'azure538'
      kubernetestffilesfolder: 'CreateKubernetesClusterdev'
      gituser: naveen kumar
      gitemailid: naveen538.k@gmail.com
    secrets: inherit
    
  call-kubernetescluster-creation-test:
    name: Create Kubernetes Cluster in Test environment
    uses: Naveen-Kollu/ApoTestingCP/.github/workflows/createKubernetesCluster.yml@main
    with:
      environment: 'azure538test'
      kubernetestffilesfolder: 'CreateKubernetesClustertest'
      gituser: naveen kumar
      gitemailid: naveen538.k@gmail.com
    secrets: inherit  
